version: '3.3'

services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html
      - ./logs:/var/log/apache2
    ports:
      - 8000:80
    environment:
      PHP_INI_ERROR_LOG: /var/log/apache2/error.log

  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 6033:3306
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
volumes:
  logs:
    driver: local
